// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace repasoFinal2.DATA.Models;

public partial class Viaje
{
    public int Id { get; set; }

    public string Destino { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public decimal PrecioTotal { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<ViajeDetalle> ViajeDetalles { get; set; } = new List<ViajeDetalle>();
}