// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace repasoFinal2.DATA.Models;

public partial class ViajeDetalle
{
    public int Id { get; set; }

    public int ViajeId { get; set; }

    public int ExcursionId { get; set; }

    public int CantidadPersonas { get; set; }

    public decimal Subtotal { get; set; }

    public virtual Excursione Excursion { get; set; }

    public virtual Viaje Viaje { get; set; }
}